apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-cleaning-results
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1500Gi
  storageClassName: shared
