apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-cleaning-processed
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: shared
