apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-cleaning-notebooks
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: shared
